name: UnBlender_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.8
  - snakemake=7.25.0
  - anndata=0.8.0
  - pandas=1.5.2
  - matplotlib=3.5.3
  - numpy=1.23.4
  - yaml=0.2.5
  - scanpy=1.9.1
  - r-base=4.5
  - r-ggplot2=4.0.0
  - r-dplyr=1.1.4
  - r-tidyr=1.3.1
  - r-ggpubr=0.6.2
  - r-RColorBrewer=1.1.3
  - r-cowplot=1.2.0