# Example config file for UnBlender pipeline

# Run with: snakemake -c1 --configfile configfilename
# from the directory that contains the Snakemake file 

# Locations
config_filename: "/home/user/path/to/example_config.yml" # absolute path to this file
output_dir: "/home/user/path/to/output_dir/" # absolute path to directory

# Docker credentials
email: "my.email.address@example.com" # The email address that matches your CIBERSORTx token
token: "48297a506d1ebd24c3caf82b95f73108" # Example, you'll need to request a token for your own use!

# Analysis parameters
sample_type: "parenchyma" # options: parenchyma, bronchial_brush, nasal_brush, bronchial_biopsy
filter_reference: 'no_filter' # options: 'no_filter' or absolute path to file

cell_types: # Cell type selection to deconvolute into
  - - "ann_level_3"
    - "EC arterial"

  - - "ann_level_3"
    - "EC capillary"

  - - "ann_level_3"
    - "EC venous"

  - - "ann_level_2"
    - "Lymphatic EC"

  - - "ann_level_3"
    - - "Basal"
      - "Secretory"

  - - "ann_level_3"
    - "Multiciliated lineage"

  - - "ann_level_3"
    - "AT2"

  - - "ann_level_3"
    - "B cell lineage"

  - - "ann_level_3"
    - - "Innate lymphoid cell NK"
      - "T cell lineage"

  - - "ann_level_3"
    - "Dendritic cells"

  - - "ann_level_4"
    - "Alveolar macrophages"

  - - "ann_level_4"
    - "Interstitial macrophages"

  - - "ann_level_2"
    - "Fibroblast lineage"

  - - "ann_level_2"
    - "Smooth muscle"

  - - "ann_level_3"
    - "Mast cells"

  - - "ann_level_3"
    - "Monocytes"